-- Axiem schema - combined migrations 005-011 (idempotent). Paste into Supabase SQL Editor -> Run.

-- ===== 005_executions_trades.sql =====
-- ─────────────────────────────────────────────────────────────────────────────
-- Migration 005: executions + trades tables + reconstruction RPCs
-- ─────────────────────────────────────────────────────────────────────────────
-- Run via: supabase db push  (or paste into Supabase SQL editor)
-- Safe to re-run: all statements use IF NOT EXISTS / CREATE OR REPLACE.
-- ─────────────────────────────────────────────────────────────────────────────

-- ── executions ────────────────────────────────────────────────────────────────
-- Stores every raw fill received from any broker.
-- Immutable once inserted — reconstruction reads but never modifies this table.
--
-- Deduplication invariant:
--   UNIQUE(user_id, synthetic_id) ensures each broker fill is stored exactly
--   once per user.  Concurrent inserts for the same fill safely conflict and
--   one wins; the other is a no-op (ON CONFLICT DO NOTHING in the app layer).

CREATE TABLE IF NOT EXISTS executions (
  id              UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id         UUID         NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,

  -- synthetic_id = `${accountId}:${brokerExecId}` — globally unique per user's fills
  -- This is the dedup key and the reconstructor's Execution.id field.
  synthetic_id    TEXT         NOT NULL,

  broker_exec_id  TEXT         NOT NULL,      -- broker's own fill ID (number as string)
  account_id      TEXT         NOT NULL,      -- broker account ID (string for portability)
  symbol          TEXT         NOT NULL,      -- instrument symbol or contractId for MVP
  side            TEXT         NOT NULL CHECK (side IN ('buy', 'sell')),
  qty             INTEGER      NOT NULL CHECK (qty > 0),
  price           NUMERIC(14,6) NOT NULL CHECK (price > 0),
  fill_timestamp  TIMESTAMPTZ  NOT NULL,      -- broker clock — used for reconstruction ordering
  order_id        TEXT,                        -- nullable: absent = reconstructor creates synthetic order
  received_at     BIGINT       NOT NULL,      -- our wall clock (Date.now()), cursor fallback
  raw_payload     JSONB        NOT NULL DEFAULT '{}',  -- original broker object, unmodified
  created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

  CONSTRAINT executions_user_synthetic_uniq UNIQUE (user_id, synthetic_id)
);

-- Reconstruction index: covers the exact WHERE + ORDER BY used by the RPC.
-- Partial index on user_id + symbol + account_id to avoid full-table scans.
CREATE INDEX IF NOT EXISTS executions_reconstruction_idx
  ON executions (user_id, symbol, account_id, fill_timestamp ASC, synthetic_id ASC);

-- ── trades ────────────────────────────────────────────────────────────────────
-- Materialised output of trade reconstruction.
-- Fully derived from executions — can always be regenerated by re-running
-- reconstructTrades() over the executions for a position.
--
-- Invariant: reconstruction_status = 'skipped' means the trade is a complex
-- reversal and MUST be excluded from all P&L aggregations.
-- Queries should always add:  AND reconstruction_status = 'ok'

CREATE TABLE IF NOT EXISTS trades (
  id                    UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id               UUID         NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  account_id            TEXT         NOT NULL,
  symbol                TEXT         NOT NULL,
  direction             TEXT         NOT NULL CHECK (direction IN ('long', 'short')),
  opened_at             TIMESTAMPTZ  NOT NULL,    -- first entry fill timestamp
  closed_at             TIMESTAMPTZ,               -- last exit fill timestamp; NULL = open position
  entry_price           NUMERIC(14,6),             -- order-weighted avg entry; NULL for complex_reversal
  exit_price            NUMERIC(14,6),             -- order-weighted avg exit; NULL for open / reversal
  max_size              INTEGER      NOT NULL CHECK (max_size > 0),
  execution_ids         TEXT[]       NOT NULL DEFAULT '{}',   -- Execution.id values in this trade
  reconstruction_status TEXT         NOT NULL DEFAULT 'ok'
                          CHECK (reconstruction_status IN ('ok', 'skipped')),
  behavioral_tags       TEXT[]       NOT NULL DEFAULT '{}',   -- ["complex_reversal"], ["open"], etc.
  pnl_points            NUMERIC(14,6),             -- raw price-delta × qty; NULL for open / reversal
  net_pnl               NUMERIC(14,6),             -- USD; NULL if instrument unknown / open / reversal
  created_at            TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- Session query index: dashboard loads trades for a user ordered by time.
CREATE INDEX IF NOT EXISTS trades_session_idx
  ON trades (user_id, symbol, account_id, opened_at DESC);

-- Partial index for fast P&L aggregation (excludes skipped trades).
CREATE INDEX IF NOT EXISTS trades_pnl_idx
  ON trades (user_id, opened_at DESC)
  WHERE reconstruction_status = 'ok' AND closed_at IS NOT NULL;

-- updated_at trigger
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger
    WHERE tgname = 'trades_updated_at' AND tgrelid = 'trades'::regclass
  ) THEN
    CREATE TRIGGER trades_updated_at
      BEFORE UPDATE ON trades
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END $$;


-- ── RPC: read_executions_for_reconstruction ───────────────────────────────────
--
-- Reads all executions for a position, sorted, with an advisory lock.
--
-- Lock mechanism
-- ──────────────
-- pg_advisory_xact_lock(key1 int, key2 int) acquires a transaction-scoped
-- advisory lock using two int4 keys.  It blocks until the lock is available
-- and releases automatically when the calling transaction commits or rolls back.
--
-- Two concurrent calls with the same (p_user_id, p_symbol, p_account_id) will
-- serialise: the second waits until the first's transaction ends.  This ensures
-- each caller receives a consistent snapshot — the second caller will always
-- see at least as many rows as the first (inserts are committed before the
-- first call's lock was released).
--
-- hashtext(text) → int4.  Using two keys (user_id, symbol+account) keeps the
-- lock space sparse and reduces false-sharing between unrelated positions.
--
-- SECURITY DEFINER: runs as the function owner (postgres) to bypass RLS.
-- The app layer has already authenticated the caller before invoking this.

CREATE OR REPLACE FUNCTION read_executions_for_reconstruction(
  p_user_id    UUID,
  p_symbol     TEXT,
  p_account_id TEXT
)
RETURNS SETOF executions
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  -- Acquire advisory lock scoped to this (user, symbol, account) triple.
  -- Two reconstructions for the same position serialise here.
  PERFORM pg_advisory_xact_lock(
    hashtext(p_user_id::text),
    hashtext(p_symbol || '|' || p_account_id)
  );

  -- Return sorted executions — ORDER BY enforces INV-5 for the reconstructor.
  RETURN QUERY
    SELECT *
    FROM   executions
    WHERE  user_id    = p_user_id
      AND  symbol     = p_symbol
      AND  account_id = p_account_id
    ORDER BY fill_timestamp ASC, synthetic_id ASC;
END;
$$;

COMMENT ON FUNCTION read_executions_for_reconstruction IS
  'Advisory-locked read of executions for one position. '
  'Serialises concurrent reconstruction triggers for the same (user, symbol, account). '
  'Returns rows sorted (fill_timestamp ASC, synthetic_id ASC) as required by reconstructTrades().';


-- ── RPC: replace_position_trades ─────────────────────────────────────────────
--
-- Atomically replaces all trades for a position with a fresh reconstruction set.
--
-- DELETE + INSERT in a single transaction means there is never a window where
-- a position has zero trade rows.  The app layer passes the full trade set as
-- JSONB so both operations are committed together.
--
-- JSONB null handling:
--   PostgreSQL's ->> operator returns SQL NULL when the JSONB value is JSON null.
--   Casting SQL NULL to a typed column (timestamptz, numeric, etc.) yields SQL NULL.
--   This means null fields in the TypeScript payload round-trip correctly.
--
-- SECURITY DEFINER: same reasoning as above.

CREATE OR REPLACE FUNCTION replace_position_trades(
  p_user_id    UUID,
  p_symbol     TEXT,
  p_account_id TEXT,
  p_trades     JSONB
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  -- Step 1: Remove all existing trades for this position.
  DELETE FROM trades
  WHERE  user_id    = p_user_id
    AND  symbol     = p_symbol
    AND  account_id = p_account_id;

  -- Step 2: If nothing to insert, done.
  IF p_trades IS NULL OR jsonb_array_length(p_trades) = 0 THEN
    RETURN;
  END IF;

  -- Step 3: Insert the full reconstruction set.
  -- JSON null values cast correctly to SQL NULL for nullable columns.
  INSERT INTO trades (
    user_id,
    account_id,
    symbol,
    direction,
    opened_at,
    closed_at,
    entry_price,
    exit_price,
    max_size,
    execution_ids,
    reconstruction_status,
    behavioral_tags,
    pnl_points,
    net_pnl
  )
  SELECT
    p_user_id,
    p_account_id,
    p_symbol,
    (t->>'direction')::text,
    (t->>'opened_at')::timestamptz,
    (t->>'closed_at')::timestamptz,       -- JSON null → SQL NULL ✓
    (t->>'entry_price')::numeric,          -- JSON null → SQL NULL ✓
    (t->>'exit_price')::numeric,           -- JSON null → SQL NULL ✓
    (t->>'max_size')::integer,
    ARRAY(SELECT jsonb_array_elements_text(t->'execution_ids')),
    COALESCE((t->>'reconstruction_status')::text, 'ok'),
    ARRAY(SELECT jsonb_array_elements_text(t->'behavioral_tags')),
    (t->>'pnl_points')::numeric,           -- JSON null → SQL NULL ✓
    (t->>'net_pnl')::numeric               -- JSON null → SQL NULL ✓
  FROM jsonb_array_elements(p_trades) AS t;
END;
$$;

COMMENT ON FUNCTION replace_position_trades IS
  'Atomically replaces all trades for (user_id, symbol, account_id) in one transaction. '
  'Called by the TypeScript ingest layer after reconstruction completes. '
  'DELETE + INSERT ensures no partial-write window.';


-- ── Row Level Security ────────────────────────────────────────────────────────
-- Enable RLS on both tables.  RPCs run as SECURITY DEFINER (postgres) and bypass
-- RLS.  Direct client queries (dashboard) are filtered by user_id.

ALTER TABLE executions ENABLE ROW LEVEL SECURITY;
ALTER TABLE trades     ENABLE ROW LEVEL SECURITY;

-- Users can only read their own data.
-- The service-role client (used by ingest) bypasses RLS entirely.

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'executions' AND policyname = 'executions_owner'
  ) THEN
    CREATE POLICY executions_owner ON executions
      FOR ALL USING (auth.uid() = user_id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'trades' AND policyname = 'trades_owner'
  ) THEN
    CREATE POLICY trades_owner ON trades
      FOR ALL USING (auth.uid() = user_id);
  END IF;
END $$;


-- ===== 006_event_sourcing.sql =====
-- ─────────────────────────────────────────────────────────────────────────────
-- Migration 006: event_log table — the sole source of truth
-- ─────────────────────────────────────────────────────────────────────────────
-- Run via: supabase db push  (or paste into Supabase SQL editor)
-- Safe to re-run: all statements use IF NOT EXISTS / CREATE OR REPLACE.
-- ─────────────────────────────────────────────────────────────────────────────
--
-- Architecture
-- ────────────
-- The event_log is append-only and immutable.  All derived state
-- (executions, trades, positions, behavior) is regenerable by replaying
-- events in event_sequence_id order.
--
-- Ordering invariant (EV-3)
-- ──────────────────────────
-- event_sequence_id BIGINT GENERATED ALWAYS AS IDENTITY provides a
-- strictly monotonic, per-database sequence.  This is the ONLY ordering
-- dimension used by the reconstruction pipeline.  fill_timestamp (broker
-- clock) is stored as payload metadata and is never used for ordering.
--
-- Deduplication invariant (EV-4)
-- ────────────────────────────────
-- broker_event_hash = `${broker}:${accountId}:${brokerExecId}` is the
-- UNIQUE dedup key per user.  A duplicate insert fails with error 23505;
-- the app layer treats this as a clean no-op.
-- ─────────────────────────────────────────────────────────────────────────────

-- ── event_log ─────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS event_log (
  -- DB-assigned strictly-monotonic ordering key.
  -- GENERATED ALWAYS means the app layer cannot supply or override this value.
  -- It advances even for aborted transactions — gaps are normal and expected.
  event_sequence_id  BIGINT       GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

  id                 UUID         NOT NULL DEFAULT gen_random_uuid(),
  user_id            UUID         NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,

  -- Broker identifier: "tradovate" for MVP.  Used in broker_event_hash.
  broker             TEXT         NOT NULL,

  -- Broker account ID.  TEXT for portability (Tradovate uses integers but
  -- other brokers may use strings).
  account_id         TEXT         NOT NULL,

  -- Canonical instrument symbol (e.g. "ESM5").  May be contractId string for
  -- MVP if the extension hasn't resolved it yet.
  instrument         TEXT         NOT NULL,

  -- Event type discriminator.
  event_type         TEXT         NOT NULL
                       CHECK (event_type IN ('execution', 'correction', 'position_reset')),

  -- Deduplication key: `${broker}:${accountId}:${brokerExecId}`.
  -- UNIQUE(user_id, broker_event_hash) is the sole dedup mechanism.
  -- The app layer does ON CONFLICT / detects 23505 and silently ignores duplicates.
  broker_event_hash  TEXT         NOT NULL,

  -- Typed event payload as JSONB.
  -- For execution: { broker_exec_id, account_id, symbol, side, qty, price,
  --                  fill_timestamp, order_id }
  -- JSON null values for nullable fields round-trip as SQL NULL via ->> cast.
  payload            JSONB        NOT NULL DEFAULT '{}',

  -- Original broker object, verbatim.  Never modified.  Retained for audit /
  -- schema change recovery.
  raw_payload        JSONB        NOT NULL DEFAULT '{}',

  -- Wall-clock time this row was written.
  created_at         TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

  CONSTRAINT event_log_user_hash_uniq UNIQUE (user_id, broker_event_hash)
);

-- ── Indexes ───────────────────────────────────────────────────────────────────

-- Reconstruction read path: covers WHERE user_id + instrument + account_id
-- with ORDER BY event_sequence_id ASC.
CREATE INDEX IF NOT EXISTS event_log_reconstruction_idx
  ON event_log (user_id, instrument, account_id, event_sequence_id ASC);

-- Replay path: read all events for a user in sequence order.
CREATE INDEX IF NOT EXISTS event_log_user_seq_idx
  ON event_log (user_id, event_sequence_id ASC);

-- Dedup lookup (covered by the UNIQUE constraint, but explicit for clarity):
-- UNIQUE(user_id, broker_event_hash) above creates an implicit index.

-- ── RPC: read_events_for_reconstruction ──────────────────────────────────────
--
-- Advisory-locked, sorted read of all events for one position.
--
-- Advisory lock mechanism
-- ────────────────────────
-- pg_advisory_xact_lock(key1 int4, key2 int4) acquires a transaction-scoped
-- lock.  Two concurrent calls with the same (p_user_id, p_instrument,
-- p_account_id) serialise: the second waits until the first's transaction
-- ends.  The second call then reads at least as many events as the first
-- (monotonically increasing snapshot).
--
-- This serialisation ensures that concurrent reconstruction attempts always
-- converge: the last writer wins (via replace_position_trades DELETE+INSERT),
-- and the last writer had the most events.
--
-- SECURITY DEFINER: runs as function owner (postgres) to bypass RLS.
-- The app layer has authenticated the caller before invoking this RPC.

CREATE OR REPLACE FUNCTION read_events_for_reconstruction(
  p_user_id    UUID,
  p_instrument TEXT,
  p_account_id TEXT
)
RETURNS SETOF event_log
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  -- Serialise concurrent reconstruction for the same position.
  -- hashtext(text) → int4.  Two keys reduces false-sharing between positions.
  PERFORM pg_advisory_xact_lock(
    hashtext(p_user_id::text),
    hashtext(p_instrument || '|' || p_account_id)
  );

  -- Return events in strict event_sequence_id order (EV-3).
  -- ORDER BY fill_timestamp is intentionally absent — event_sequence_id only.
  RETURN QUERY
    SELECT *
    FROM   event_log
    WHERE  user_id    = p_user_id
      AND  instrument = p_instrument
      AND  account_id = p_account_id
    ORDER BY event_sequence_id ASC;
END;
$$;

COMMENT ON FUNCTION read_events_for_reconstruction IS
  'Advisory-locked read of event_log for one position. '
  'Serialises concurrent reconstruction triggers for (user, instrument, account). '
  'Returns rows in strict event_sequence_id ASC order (EV-3). '
  'fill_timestamp is payload metadata; it is never used for ordering here.';


-- ── RPC: replay_position ─────────────────────────────────────────────────────
--
-- Full replay for a single position: delete all derived trades and signal
-- the app layer to run reconstruction from scratch.
--
-- The RPC itself only clears derived state — the TypeScript replay pathway
-- (lib/replay.ts) calls this, then calls readEventsForPosition + reduce +
-- reconstruct + replace to regenerate trades.
--
-- SECURITY DEFINER: same reasoning as above.

CREATE OR REPLACE FUNCTION replay_position(
  p_user_id    UUID,
  p_instrument TEXT,
  p_account_id TEXT
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  -- Clear derived trades for this position.
  -- The trades table is a materialised view of reconstruction output;
  -- deleting here is safe — all source data is in event_log.
  DELETE FROM trades
  WHERE  user_id    = p_user_id
    AND  symbol     = p_instrument
    AND  account_id = p_account_id;
END;
$$;

COMMENT ON FUNCTION replay_position IS
  'Delete all derived trades for a position so it can be reconstructed from scratch. '
  'Called by lib/replay.ts before re-running the full event reduce + reconstruct cycle. '
  'event_log rows are never deleted — they are the source of truth.';


-- ── Row Level Security ────────────────────────────────────────────────────────
-- RPCs run as SECURITY DEFINER and bypass RLS.
-- Direct client queries (dashboard, admin panel) are filtered by user_id.

ALTER TABLE event_log ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'event_log' AND policyname = 'event_log_owner'
  ) THEN
    CREATE POLICY event_log_owner ON event_log
      FOR ALL USING (auth.uid() = user_id);
  END IF;
END $$;


-- ===== 007_observability.sql =====
-- ─────────────────────────────────────────────────────────────────────────────
-- Migration 007: reconstruction observability, replay safety, snapshot stub
-- ─────────────────────────────────────────────────────────────────────────────
-- Run via: supabase db push  (or paste into Supabase SQL editor)
-- Safe to re-run: all statements use IF NOT EXISTS / CREATE OR REPLACE.
-- ─────────────────────────────────────────────────────────────────────────────
--
-- This migration adds:
--   1. position_rebuild_state  — tracks reconstruction freshness per position
--   2. RPCs for rebuild state lifecycle (started / finished / replay lock)
--   3. position_snapshots      — stub table for future snapshot optimisation
--   4. Health query helpers
-- ─────────────────────────────────────────────────────────────────────────────

-- ── 1. position_rebuild_state ─────────────────────────────────────────────────
--
-- One row per (user_id, account_id, instrument) triple.
-- Tracks the reconstruction freshness of the materialised trades for that position.
--
-- Freshness invariant:
--   lag = MAX(event_sequence_id WHERE user_id+account_id+instrument) - last_rebuilt_event_sequence_id
--   lag > 0  ↔  trades are stale and a rebuild is in progress or pending
--   lag = 0  ↔  trades are current
--   last_rebuilt IS NULL ↔  position has never been reconstructed
--
-- replay_in_progress / replay_started_at
--   Set while lib/replay.ts is running a full re-reduce for this position.
--   Ingestion continues during replay (event_log always accepts writes).
--   The UI must show a replay-in-progress indicator while this is true.

CREATE TABLE IF NOT EXISTS position_rebuild_state (
  user_id                          UUID         NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  account_id                       TEXT         NOT NULL,
  instrument                       TEXT         NOT NULL,

  -- event_sequence_id of the last event that was included in the current
  -- materialised trades.  NULL = trades have never been built for this position.
  last_rebuilt_event_sequence_id   BIGINT,

  -- Wall-clock times of the most recent rebuild cycle.
  rebuild_started_at               TIMESTAMPTZ,
  rebuild_finished_at              TIMESTAMPTZ,

  -- Monotonically incrementing rebuild counter.  Allows the UI to detect when
  -- a new rebuild has completed (count changed) vs the same rebuild.
  rebuild_count                    INTEGER      NOT NULL DEFAULT 0,

  -- True while lib/replay.ts is executing a full re-reduce for this position.
  -- Acts as a soft advisory flag (not a hard lock — the DB advisory lock is used
  -- for actual serialisation).
  replay_in_progress               BOOLEAN      NOT NULL DEFAULT FALSE,
  replay_started_at                TIMESTAMPTZ,

  created_at                       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at                       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

  PRIMARY KEY (user_id, account_id, instrument)
);

-- updated_at trigger reuses set_updated_at() from migration 005.
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger
    WHERE tgname = 'position_rebuild_state_updated_at'
      AND tgrelid = 'position_rebuild_state'::regclass
  ) THEN
    CREATE TRIGGER position_rebuild_state_updated_at
      BEFORE UPDATE ON position_rebuild_state
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END $$;

-- Index: health endpoint queries all positions for a user.
CREATE INDEX IF NOT EXISTS position_rebuild_state_user_idx
  ON position_rebuild_state (user_id);

-- RLS
ALTER TABLE position_rebuild_state ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'position_rebuild_state' AND policyname = 'position_rebuild_state_owner'
  ) THEN
    CREATE POLICY position_rebuild_state_owner ON position_rebuild_state
      FOR ALL USING (auth.uid() = user_id);
  END IF;
END $$;


-- ── 2. RPCs: rebuild state lifecycle ─────────────────────────────────────────

-- mark_rebuild_started
-- ─────────────────────
-- Called at the start of scheduleReconstruction (before advisory lock read).
-- Upserts the row, sets rebuild_started_at, clears rebuild_finished_at.
-- SECURITY DEFINER: called from the ingest pipeline which uses service role.

CREATE OR REPLACE FUNCTION mark_rebuild_started(
  p_user_id    UUID,
  p_account_id TEXT,
  p_instrument TEXT
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  INSERT INTO position_rebuild_state (
    user_id, account_id, instrument,
    rebuild_started_at, rebuild_finished_at
  ) VALUES (
    p_user_id, p_account_id, p_instrument,
    NOW(), NULL
  )
  ON CONFLICT (user_id, account_id, instrument) DO UPDATE SET
    rebuild_started_at   = NOW(),
    rebuild_finished_at  = NULL,
    updated_at           = NOW();
END;
$$;

COMMENT ON FUNCTION mark_rebuild_started IS
  'Called at the start of a reconstruction cycle. Sets rebuild_started_at, '
  'clears rebuild_finished_at. UI uses the NULL finished_at to show "Updating trades…".';


-- mark_rebuild_finished
-- ──────────────────────
-- Called after replace_position_trades completes successfully.
-- Records the highest event_sequence_id included in this rebuild.

CREATE OR REPLACE FUNCTION mark_rebuild_finished(
  p_user_id                         UUID,
  p_account_id                      TEXT,
  p_instrument                      TEXT,
  p_last_rebuilt_event_sequence_id  BIGINT
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  INSERT INTO position_rebuild_state (
    user_id, account_id, instrument,
    last_rebuilt_event_sequence_id,
    rebuild_finished_at,
    rebuild_count
  ) VALUES (
    p_user_id, p_account_id, p_instrument,
    p_last_rebuilt_event_sequence_id,
    NOW(),
    1
  )
  ON CONFLICT (user_id, account_id, instrument) DO UPDATE SET
    last_rebuilt_event_sequence_id = p_last_rebuilt_event_sequence_id,
    rebuild_finished_at            = NOW(),
    rebuild_count                  = position_rebuild_state.rebuild_count + 1,
    updated_at                     = NOW();
END;
$$;

COMMENT ON FUNCTION mark_rebuild_finished IS
  'Called after a successful reconstruction write. Records the highest '
  'event_sequence_id covered and increments rebuild_count.';


-- mark_replay_started / mark_replay_finished
-- ────────────────────────────────────────────
-- Used by lib/replay.ts to flag that a full re-reduce is in progress.
-- The UI must surface this state to prevent user confusion during replay.

DROP FUNCTION IF EXISTS mark_replay_started;
CREATE OR REPLACE FUNCTION mark_replay_started(
  p_user_id    UUID,
  p_account_id TEXT,
  p_instrument TEXT
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  INSERT INTO position_rebuild_state (
    user_id, account_id, instrument,
    replay_in_progress, replay_started_at
  ) VALUES (
    p_user_id, p_account_id, p_instrument,
    TRUE, NOW()
  )
  ON CONFLICT (user_id, account_id, instrument) DO UPDATE SET
    replay_in_progress = TRUE,
    replay_started_at  = NOW(),
    updated_at         = NOW();
END;
$$;

DROP FUNCTION IF EXISTS mark_replay_finished;
CREATE OR REPLACE FUNCTION mark_replay_finished(
  p_user_id                         UUID,
  p_account_id                      TEXT,
  p_instrument                      TEXT,
  p_last_rebuilt_event_sequence_id  BIGINT
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  INSERT INTO position_rebuild_state (
    user_id, account_id, instrument,
    last_rebuilt_event_sequence_id,
    rebuild_finished_at,
    rebuild_count,
    replay_in_progress,
    replay_started_at
  ) VALUES (
    p_user_id, p_account_id, p_instrument,
    p_last_rebuilt_event_sequence_id,
    NOW(),
    1,
    FALSE,
    NULL
  )
  ON CONFLICT (user_id, account_id, instrument) DO UPDATE SET
    last_rebuilt_event_sequence_id = p_last_rebuilt_event_sequence_id,
    rebuild_finished_at            = NOW(),
    rebuild_count                  = position_rebuild_state.rebuild_count + 1,
    replay_in_progress             = FALSE,
    replay_started_at              = NULL,
    updated_at                     = NOW();
END;
$$;


-- ── 3. Health query: get_position_health ─────────────────────────────────────
--
-- Returns per-position health metrics for a user:
--   instrument, account_id,
--   latest_event_sequence_id   (MAX in event_log for this position)
--   last_rebuilt_event_sequence_id
--   lag                        (latest - last_rebuilt; negative means never rebuilt)
--   rebuild_started_at
--   rebuild_finished_at
--   rebuild_count
--   replay_in_progress
--
-- SECURITY DEFINER: health endpoint is called by authenticated service client.

DROP FUNCTION IF EXISTS get_position_health;
CREATE OR REPLACE FUNCTION get_position_health(p_user_id UUID)
RETURNS TABLE (
  instrument                      TEXT,
  account_id                      TEXT,
  latest_event_sequence_id        BIGINT,
  last_rebuilt_event_sequence_id  BIGINT,
  lag                             BIGINT,
  rebuild_started_at              TIMESTAMPTZ,
  rebuild_finished_at             TIMESTAMPTZ,
  rebuild_count                   INTEGER,
  replay_in_progress              BOOLEAN,
  is_stale                        BOOLEAN
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT
    e.instrument,
    e.account_id,
    MAX(e.event_sequence_id)                       AS latest_event_sequence_id,
    r.last_rebuilt_event_sequence_id,
    -- lag: how many sequence IDs behind the rebuild is.
    -- If never rebuilt, treat as lag = latest (all events unprocessed).
    MAX(e.event_sequence_id) - COALESCE(r.last_rebuilt_event_sequence_id, 0) AS lag,
    r.rebuild_started_at,
    r.rebuild_finished_at,
    COALESCE(r.rebuild_count, 0)                   AS rebuild_count,
    COALESCE(r.replay_in_progress, FALSE)           AS replay_in_progress,
    -- is_stale: true if trades don't reflect all known events
    (MAX(e.event_sequence_id) > COALESCE(r.last_rebuilt_event_sequence_id, -1)) AS is_stale
  FROM event_log e
  LEFT JOIN position_rebuild_state r
    ON  r.user_id    = e.user_id
    AND r.account_id = e.account_id
    AND r.instrument = e.instrument
  WHERE e.user_id = p_user_id
  GROUP BY e.instrument, e.account_id,
           r.last_rebuilt_event_sequence_id, r.rebuild_started_at,
           r.rebuild_finished_at, r.rebuild_count, r.replay_in_progress;
END;
$$;

COMMENT ON FUNCTION get_position_health IS
  'Returns per-position reconstruction freshness for the health endpoint and UI staleness detection. '
  'lag > 0 means trades are stale. is_stale = true means the UI must show "Updating trades…".';


-- ── 4. position_snapshots (stub — future snapshot optimisation) ───────────────
--
-- SNAPSHOT MIGRATION PATH
-- ───────────────────────
-- When event_log grows large (>10k events per user), full reduce-on-every-read
-- becomes expensive.  The snapshot optimisation makes reconstruction O(events
-- since snapshot) instead of O(all events).
--
-- Design:
--   1. Periodically (e.g. every 100 events, or on a schedule) save the full
--      ReducerOutput for a position to position_snapshots.
--   2. readEventsForPosition() is replaced by:
--        a. Load latest snapshot for position.
--        b. Read only events WHERE event_sequence_id > snapshot.last_event_sequence_id.
--        c. Reduce snapshot.state + incremental events.
--   3. Snapshots are never the source of truth — they are a cache.
--      replay_position() can be called at any time to regenerate from scratch.
--   4. A snapshot is invalidated by bumping last_event_sequence_id on write.
--
-- The stub table below reserves the schema. Activate it in a future migration
-- by wiring readEventsForPositionSince() (already in lib/db/eventLog.ts) to
-- the ingest reconstruction pipeline.
--
-- IMPORTANT: Do NOT write to this table until the snapshot activation migration.
-- Reading from it before it has data will return zero rows, causing
-- readEventsForPositionSince(0, ...) which is equivalent to full reduce — safe.

CREATE TABLE IF NOT EXISTS position_snapshots (
  user_id                  UUID         NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  account_id               TEXT         NOT NULL,
  instrument               TEXT         NOT NULL,
  -- The event_sequence_id of the last event included in this snapshot.
  -- Reconstruction reads events WHERE event_sequence_id > this value.
  last_event_sequence_id   BIGINT       NOT NULL,
  -- Serialised ReducerOutput.  JSON null values cast to SQL NULL on extraction.
  state                    JSONB        NOT NULL DEFAULT '{}',
  created_at               TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  -- Only one active snapshot per position.
  PRIMARY KEY (user_id, account_id, instrument)
);

-- RLS
ALTER TABLE position_snapshots ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'position_snapshots' AND policyname = 'position_snapshots_owner'
  ) THEN
    CREATE POLICY position_snapshots_owner ON position_snapshots
      FOR ALL USING (auth.uid() = user_id);
  END IF;
END $$;


-- ===== 008_rebuild_locks.sql =====
-- ─────────────────────────────────────────────────────────────────────────────
-- Migration 008: rebuild_locks + replay_status + heartbeat
-- ─────────────────────────────────────────────────────────────────────────────
-- Run via: supabase db push  (or paste into Supabase SQL editor)
-- Safe to re-run: all statements use IF NOT EXISTS / CREATE OR REPLACE.
-- ─────────────────────────────────────────────────────────────────────────────
--
-- This migration adds:
--   1. rebuild_locks       — persistent cross-instance reconstruction lock
--   2. replay_status       — self-healing replay state machine
--   3. replay_heartbeat_at — liveness signal for in-progress replays
--   4. RPCs for lock lifecycle and stale detection
-- ─────────────────────────────────────────────────────────────────────────────

-- ── 1. rebuild_locks ─────────────────────────────────────────────────────────
--
-- Persistent, DB-backed coordination table.
-- One row per (user_id, account_id, instrument) position.
--
-- Purpose
-- ───────
-- The in-process pendingRebuilds Set in ingest.ts handles burst coalescing
-- within one process, but is invisible to other instances and evaporates on restart.
-- rebuild_locks is the CROSS-PROCESS SOURCE OF TRUTH for reconstruction state.
--
-- Rules
-- ─────
--   - Only one instance may hold 'running' status per position at a time.
--   - A lock is considered STALE if status = 'running' AND
--     now() - updated_at > 2 minutes (process crashed mid-reconstruction).
--   - Stale locks are auto-released by try_acquire_rebuild_lock.
--   - Correctness guarantee: the advisory lock inside read_events_for_reconstruction
--     serialises the actual read phase. This table is for observability + stale recovery.
--
-- Interaction with advisory lock
-- ──────────────────────────────
-- rebuild_locks is acquired BEFORE calling read_events_for_reconstruction.
-- The advisory lock (inside that RPC) handles the actual read serialisation.
-- The two layers are complementary:
--   - rebuild_locks: persistent, observable, cross-instance, stale-recoverable.
--   - advisory lock: in-transaction, low-latency, handles within-RPC serialisation.

CREATE TABLE IF NOT EXISTS rebuild_locks (
  user_id     UUID         NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  account_id  TEXT         NOT NULL,
  instrument  TEXT         NOT NULL,
  -- 'running' = reconstruction in progress; 'idle' = no active reconstruction.
  status      TEXT         NOT NULL DEFAULT 'idle'
                             CHECK (status IN ('running', 'idle')),
  -- Wall-clock time when status last became 'running'. Used for stale detection.
  locked_at   TIMESTAMPTZ,
  -- Updated on every lock operation. Stale if now() - updated_at > STALE_THRESHOLD.
  updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  PRIMARY KEY (user_id, account_id, instrument)
);

CREATE INDEX IF NOT EXISTS rebuild_locks_user_idx
  ON rebuild_locks (user_id);

ALTER TABLE rebuild_locks ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'rebuild_locks' AND policyname = 'rebuild_locks_owner'
  ) THEN
    CREATE POLICY rebuild_locks_owner ON rebuild_locks
      FOR ALL USING (auth.uid() = user_id);
  END IF;
END $$;


-- ── 2. try_acquire_rebuild_lock ──────────────────────────────────────────────
--
-- Attempts to acquire the rebuild lock for a position.
-- Returns TRUE if acquired, FALSE if another instance holds a fresh lock.
--
-- Stale lock auto-release
-- ────────────────────────
-- If the lock is held (status = 'running') but updated_at is older than
-- STALE_THRESHOLD_SECS seconds, the lock is considered stale (process crashed).
-- We atomically release-and-reacquire it.
--
-- Atomicity
-- ─────────
-- The conditional UPDATE is atomic: only one concurrent caller will succeed
-- when the lock is idle or stale — the other will see rows_affected = 0.
-- This uses Postgres row-level locking naturally.
--
-- SECURITY DEFINER: called by the ingest pipeline via service client.

CREATE OR REPLACE FUNCTION try_acquire_rebuild_lock(
  p_user_id    UUID,
  p_account_id TEXT,
  p_instrument TEXT,
  p_stale_secs INTEGER DEFAULT 120  -- 2 minutes
)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_rows INTEGER;
BEGIN
  -- Upsert the row if it doesn't exist yet (first time this position is seen).
  INSERT INTO rebuild_locks (user_id, account_id, instrument, status, locked_at, updated_at)
  VALUES (p_user_id, p_account_id, p_instrument, 'idle', NULL, NOW())
  ON CONFLICT (user_id, account_id, instrument) DO NOTHING;

  -- Attempt to acquire: update to 'running' only if currently idle OR stale.
  -- Stale = running but updated_at older than stale threshold.
  UPDATE rebuild_locks SET
    status     = 'running',
    locked_at  = NOW(),
    updated_at = NOW()
  WHERE user_id    = p_user_id
    AND account_id = p_account_id
    AND instrument = p_instrument
    AND (
      status = 'idle'
      OR (status = 'running' AND NOW() - updated_at > make_interval(secs => p_stale_secs))
    );

  GET DIAGNOSTICS v_rows = ROW_COUNT;
  RETURN v_rows > 0;
END;
$$;

COMMENT ON FUNCTION try_acquire_rebuild_lock IS
  'Non-blocking lock acquisition for reconstruction. Returns TRUE if acquired. '
  'Auto-releases stale locks (running for > p_stale_secs seconds without heartbeat). '
  'Called before scheduling reconstruction; complements the advisory lock in the read RPC.';


-- ── 3. release_rebuild_lock ──────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION release_rebuild_lock(
  p_user_id    UUID,
  p_account_id TEXT,
  p_instrument TEXT
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  UPDATE rebuild_locks SET
    status     = 'idle',
    locked_at  = NULL,
    updated_at = NOW()
  WHERE user_id    = p_user_id
    AND account_id = p_account_id
    AND instrument = p_instrument;
END;
$$;


-- ── 4. heartbeat_rebuild_lock ────────────────────────────────────────────────
--
-- Prevents stale detection for long-running operations (large replays).
-- Called periodically during replay (e.g., every 30 seconds or per batch).

CREATE OR REPLACE FUNCTION heartbeat_rebuild_lock(
  p_user_id    UUID,
  p_account_id TEXT,
  p_instrument TEXT
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  UPDATE rebuild_locks SET
    updated_at = NOW()
  WHERE user_id    = p_user_id
    AND account_id = p_account_id
    AND instrument = p_instrument
    AND status     = 'running';
END;
$$;


-- ── 5. Add replay_status + replay_heartbeat_at to position_rebuild_state ─────
--
-- Upgrades position_rebuild_state (created in migration 007) with:
--   replay_status        — enum for self-healing replay state machine
--   replay_heartbeat_at  — liveness signal; stale if > 2 min behind NOW()
--
-- replay_status transitions:
--   (absent) → running   on replay start
--   running  → completed on replay finish
--   running  → failed    on replay exception
--   running  → stale     detected by health endpoint when heartbeat is old
--   stale    → running   on retry replay
--   failed   → running   on retry replay
--
-- The health endpoint surfaces 'stale' and 'failed' as "Replay interrupted — recovering".

ALTER TABLE position_rebuild_state
  ADD COLUMN IF NOT EXISTS replay_status TEXT
    DEFAULT 'completed'
    CHECK (replay_status IN ('running', 'completed', 'stale', 'failed')),
  ADD COLUMN IF NOT EXISTS replay_heartbeat_at TIMESTAMPTZ;


-- ── 6. mark_replay_started: update to set replay_status ──────────────────────

DROP FUNCTION IF EXISTS mark_replay_started;
CREATE OR REPLACE FUNCTION mark_replay_started(
  p_user_id    UUID,
  p_account_id TEXT,
  p_instrument TEXT
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  INSERT INTO position_rebuild_state (
    user_id, account_id, instrument,
    replay_in_progress, replay_started_at,
    replay_status, replay_heartbeat_at
  ) VALUES (
    p_user_id, p_account_id, p_instrument,
    TRUE, NOW(),
    'running', NOW()
  )
  ON CONFLICT (user_id, account_id, instrument) DO UPDATE SET
    replay_in_progress  = TRUE,
    replay_started_at   = NOW(),
    replay_status       = 'running',
    replay_heartbeat_at = NOW(),
    updated_at          = NOW();
END;
$$;


-- ── 7. heartbeat_replay: keep replay alive during large replay operations ─────

CREATE OR REPLACE FUNCTION heartbeat_replay(
  p_user_id    UUID,
  p_account_id TEXT,
  p_instrument TEXT
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  UPDATE position_rebuild_state SET
    replay_heartbeat_at = NOW(),
    updated_at          = NOW()
  WHERE user_id    = p_user_id
    AND account_id = p_account_id
    AND instrument = p_instrument
    AND replay_status = 'running';
END;
$$;


-- ── 8. mark_replay_finished: updated to set replay_status = completed ─────────

DROP FUNCTION IF EXISTS mark_replay_finished;
CREATE OR REPLACE FUNCTION mark_replay_finished(
  p_user_id                         UUID,
  p_account_id                      TEXT,
  p_instrument                      TEXT,
  p_last_rebuilt_event_sequence_id  BIGINT
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  INSERT INTO position_rebuild_state (
    user_id, account_id, instrument,
    last_rebuilt_event_sequence_id,
    rebuild_finished_at,
    rebuild_count,
    replay_in_progress,
    replay_started_at,
    replay_status,
    replay_heartbeat_at
  ) VALUES (
    p_user_id, p_account_id, p_instrument,
    p_last_rebuilt_event_sequence_id,
    NOW(), 1,
    FALSE, NULL,
    'completed', NULL
  )
  ON CONFLICT (user_id, account_id, instrument) DO UPDATE SET
    last_rebuilt_event_sequence_id = p_last_rebuilt_event_sequence_id,
    rebuild_finished_at            = NOW(),
    rebuild_count                  = position_rebuild_state.rebuild_count + 1,
    replay_in_progress             = FALSE,
    replay_started_at              = NULL,
    replay_status                  = 'completed',
    replay_heartbeat_at            = NULL,
    updated_at                     = NOW();
END;
$$;


-- ── 9. mark_replay_failed: for explicit failure recording ────────────────────

CREATE OR REPLACE FUNCTION mark_replay_failed(
  p_user_id    UUID,
  p_account_id TEXT,
  p_instrument TEXT
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  INSERT INTO position_rebuild_state (
    user_id, account_id, instrument,
    replay_in_progress,
    replay_status,
    replay_heartbeat_at
  ) VALUES (
    p_user_id, p_account_id, p_instrument,
    FALSE,
    'failed',
    NULL
  )
  ON CONFLICT (user_id, account_id, instrument) DO UPDATE SET
    replay_in_progress  = FALSE,
    replay_status       = 'failed',
    replay_heartbeat_at = NULL,
    updated_at          = NOW();
END;
$$;


-- ── 10. get_position_health: update stale detection to use replay_status ──────
--
-- Re-creates the function from migration 007 with replay_status + stale logic.
-- A replay is STALE if replay_status = 'running' AND heartbeat > 2 min old.
-- The function auto-detects this and includes it in the result.

DROP FUNCTION IF EXISTS get_position_health;
CREATE OR REPLACE FUNCTION get_position_health(p_user_id UUID)
RETURNS TABLE (
  instrument                      TEXT,
  account_id                      TEXT,
  latest_event_sequence_id        BIGINT,
  last_rebuilt_event_sequence_id  BIGINT,
  lag                             BIGINT,
  rebuild_started_at              TIMESTAMPTZ,
  rebuild_finished_at             TIMESTAMPTZ,
  rebuild_count                   INTEGER,
  replay_in_progress              BOOLEAN,
  replay_status                   TEXT,
  replay_heartbeat_at             TIMESTAMPTZ,
  is_stale                        BOOLEAN,
  -- True if replay_status = 'running' AND heartbeat is older than 2 minutes.
  is_replay_stuck                 BOOLEAN
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT
    e.instrument,
    e.account_id,
    MAX(e.event_sequence_id)                       AS latest_event_sequence_id,
    r.last_rebuilt_event_sequence_id,
    MAX(e.event_sequence_id) - COALESCE(r.last_rebuilt_event_sequence_id, 0) AS lag,
    r.rebuild_started_at,
    r.rebuild_finished_at,
    COALESCE(r.rebuild_count, 0)                   AS rebuild_count,
    COALESCE(r.replay_in_progress, FALSE)           AS replay_in_progress,
    COALESCE(r.replay_status, 'completed')          AS replay_status,
    r.replay_heartbeat_at,
    (MAX(e.event_sequence_id) > COALESCE(r.last_rebuilt_event_sequence_id, -1)) AS is_stale,
    -- Replay is stuck if status = 'running' and heartbeat hasn't updated in 2 min
    (
      COALESCE(r.replay_status, 'completed') = 'running'
      AND r.replay_heartbeat_at IS NOT NULL
      AND NOW() - r.replay_heartbeat_at > INTERVAL '2 minutes'
    ) AS is_replay_stuck
  FROM event_log e
  LEFT JOIN position_rebuild_state r
    ON  r.user_id    = e.user_id
    AND r.account_id = e.account_id
    AND r.instrument = e.instrument
  WHERE e.user_id = p_user_id
  GROUP BY e.instrument, e.account_id,
           r.last_rebuilt_event_sequence_id, r.rebuild_started_at,
           r.rebuild_finished_at, r.rebuild_count, r.replay_in_progress,
           r.replay_status, r.replay_heartbeat_at;
END;
$$;

COMMENT ON FUNCTION get_position_health IS
  'Returns per-position reconstruction and replay health. '
  'is_replay_stuck = true triggers "Replay interrupted — recovering" UI state. '
  'is_stale = true triggers "Updating trades…" UI state.';


-- ===== 009_sessions.sql =====
-- ─────────────────────────────────────────────────────────────────────────────
-- Migration 009: sessions (Phase 0 — Behavioural Intelligence)
-- ─────────────────────────────────────────────────────────────────────────────
-- Run via: supabase db push  (or paste into the Supabase SQL editor)
-- Safe to re-run: all statements use IF NOT EXISTS / CREATE OR REPLACE.
--
-- ADDITIVE & NON-DESTRUCTIVE
-- ──────────────────────────
-- This migration ONLY adds a new derived table + one RPC. It does NOT touch
-- event_log, executions, trades, position_rebuild_state, position_snapshots,
-- or rebuild_locks. No existing column, index, policy, or function is altered.
--
-- Architecture
-- ────────────
-- `sessions` is a DERIVED, fully-recomputable materialised view over `trades`:
--
--     event_log (truth) → trades (derived) → sessions (derived, this table)
--
-- It is NOT a source of truth. Every row can be regenerated by running
-- lib/sessions/segment.ts over the user's trades (rebuildSessionsFromTrades).
-- session_id is a deterministic content hash supplied by the app layer, so the
-- same trades always yield the same ids. The natural key
-- (user_id, account_id, start_ts) is the stable reference for downstream layers.
-- ─────────────────────────────────────────────────────────────────────────────

-- ── sessions ──────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS sessions (
  -- Deterministic UUIDv5-style hash of (user, account, start_ts, first_trade_id).
  -- Supplied by the app layer — NOT a random default.
  session_id             UUID         PRIMARY KEY,

  user_id                UUID         NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  account_id             TEXT         NOT NULL,

  -- Session bounds (broker clock, surfaced via trades.opened_at / closed_at).
  start_ts               TIMESTAMPTZ  NOT NULL,   -- first trade opened_at
  end_ts                 TIMESTAMPTZ  NOT NULL,   -- last flat point, or last activity if open

  trade_count            INTEGER      NOT NULL CHECK (trade_count >= 0),

  -- Provenance (TEXT, intentionally NOT a FK to trades: sessions are a derived
  -- cache and must survive trades being replaced/regenerated by replay).
  first_trade_id         TEXT         NOT NULL,
  last_trade_id          TEXT         NOT NULL,

  status                 TEXT         NOT NULL DEFAULT 'closed'
                           CHECK (status IN ('open', 'provisional', 'closed')),

  -- True iff trade_count >= analytics threshold (default 4). Ineligible sessions
  -- are still stored; downstream analytics simply exclude them.
  eligible_for_analysis  BOOLEAN      NOT NULL DEFAULT FALSE,

  -- Phase 1 placeholders. NULL in Phase 0.
  feature_vector         JSONB,
  outcome                JSONB,

  computed_at            TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

  -- Stable natural key — prevents duplicate sessions for the same start.
  CONSTRAINT sessions_user_account_start_uniq UNIQUE (user_id, account_id, start_ts)
);

-- Query index: list a user's sessions (optionally by account) most-recent first.
CREATE INDEX IF NOT EXISTS sessions_user_account_idx
  ON sessions (user_id, account_id, start_ts DESC);

-- Analytics index: eligible sessions only (Phase 1+ baseline/correlation reads).
CREATE INDEX IF NOT EXISTS sessions_eligible_idx
  ON sessions (user_id, account_id, start_ts DESC)
  WHERE eligible_for_analysis = TRUE;


-- ── RPC: replace_user_sessions ────────────────────────────────────────────────
--
-- Atomically replaces ALL sessions for a user with a freshly recomputed set.
-- DELETE + INSERT in a single transaction → idempotent, no duplicate rows, no
-- partial-write window. Re-runnable any number of times.
--
-- The app layer (lib/sessions/segment.ts) computes the full deterministic set
-- and passes it as JSONB. JSON null → SQL NULL via the same ->> cast pattern
-- used by replace_position_trades.
--
-- SECURITY DEFINER: called by the backfill / maintenance pathway using the
-- service-role client, which has already authenticated the caller.

CREATE OR REPLACE FUNCTION replace_user_sessions(
  p_user_id   UUID,
  p_sessions  JSONB
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  -- Step 1: clear all existing sessions for this user.
  DELETE FROM sessions WHERE user_id = p_user_id;

  -- Step 2: nothing to insert → done (a user with no trades has no sessions).
  IF p_sessions IS NULL OR jsonb_array_length(p_sessions) = 0 THEN
    RETURN;
  END IF;

  -- Step 3: insert the recomputed set.
  INSERT INTO sessions (
    session_id, user_id, account_id,
    start_ts, end_ts, trade_count,
    first_trade_id, last_trade_id,
    status, eligible_for_analysis,
    feature_vector, outcome
  )
  SELECT
    (s->>'session_id')::uuid,
    p_user_id,
    (s->>'account_id')::text,
    (s->>'start_ts')::timestamptz,
    (s->>'end_ts')::timestamptz,
    (s->>'trade_count')::integer,
    (s->>'first_trade_id')::text,
    (s->>'last_trade_id')::text,
    (s->>'status')::text,
    (s->>'eligible_for_analysis')::boolean,
    CASE WHEN s->'feature_vector' IS NULL OR s->'feature_vector' = 'null'::jsonb
         THEN NULL ELSE s->'feature_vector' END,
    CASE WHEN s->'outcome' IS NULL OR s->'outcome' = 'null'::jsonb
         THEN NULL ELSE s->'outcome' END
  FROM jsonb_array_elements(p_sessions) AS s;
END;
$$;

COMMENT ON FUNCTION replace_user_sessions IS
  'Atomically replaces all sessions for a user (DELETE + INSERT, one transaction). '
  'Idempotent and safe to re-run. Called by lib/sessions backfill after segmentation. '
  'sessions is a derived cache — event_log/trades remain the sources of truth.';


-- ── Row Level Security ────────────────────────────────────────────────────────
-- Same pattern as every other table: RPC runs SECURITY DEFINER (bypasses RLS);
-- direct client reads are filtered to the owner.

ALTER TABLE sessions ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'sessions' AND policyname = 'sessions_owner'
  ) THEN
    CREATE POLICY sessions_owner ON sessions
      FOR ALL USING (auth.uid() = user_id);
  END IF;
END $$;


-- ===== 010_agame_baseline.sql =====
-- ─────────────────────────────────────────────────────────────────────────────
-- Migration 010: agame_baseline (Phase 1 — Behavioural Intelligence)
-- ─────────────────────────────────────────────────────────────────────────────
-- Run via: supabase db push  (or paste into the Supabase SQL editor)
-- Safe to re-run: IF NOT EXISTS / CREATE OR REPLACE throughout.
--
-- ADDITIVE & NON-DESTRUCTIVE
-- ──────────────────────────
-- Adds ONE derived table + ONE upsert RPC. Touches nothing else. The baseline
-- is a pure, recomputable median fingerprint of a (user, account)'s top
-- sessions — derived ONLY from `sessions` (their feature_vector + outcome),
-- never from trades.
--
--     sessions (derived) → agame_baseline (derived, this table)
--
-- One row per (user_id, account_id). Recompute any time; the row is replaced.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS agame_baseline (
  id                                UUID         PRIMARY KEY,   -- deterministic, app-supplied
  user_id                           UUID         NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  account_id                        TEXT         NOT NULL,

  status                            TEXT         NOT NULL DEFAULT 'calibrating'
                                      CHECK (status IN ('calibrating', 'ready')),

  -- Metadata
  session_count                     INTEGER      NOT NULL DEFAULT 0,
  min_session_threshold             INTEGER      NOT NULL DEFAULT 12,
  confidence_score                  DOUBLE PRECISION NOT NULL DEFAULT 0,
  baseline_stability_score          DOUBLE PRECISION NOT NULL DEFAULT 0,
  data_coverage_ratio               DOUBLE PRECISION NOT NULL DEFAULT 0,

  -- Structural baseline (medians of top sessions). NULL while calibrating.
  avg_trade_count                   DOUBLE PRECISION,
  median_trade_count                DOUBLE PRECISION,
  trade_count_iqr                   DOUBLE PRECISION,

  avg_inter_trade_gap_seconds       DOUBLE PRECISION,
  median_inter_trade_gap_seconds    DOUBLE PRECISION,
  pace_iqr                          DOUBLE PRECISION,

  avg_session_duration_minutes      DOUBLE PRECISION,
  median_session_duration_minutes   DOUBLE PRECISION,

  avg_position_size                 DOUBLE PRECISION,
  median_position_size              DOUBLE PRECISION,
  size_variance                     DOUBLE PRECISION,

  post_loss_trade_delay_seconds     DOUBLE PRECISION,
  post_loss_size_change_ratio       DOUBLE PRECISION,

  entry_burst_ratio                 DOUBLE PRECISION,

  -- Outcome (selection only; reported for transparency).
  avg_expectancy                    DOUBLE PRECISION,
  median_expectancy                 DOUBLE PRECISION,
  win_rate                          DOUBLE PRECISION,

  computed_at                       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

  CONSTRAINT agame_baseline_user_account_uniq UNIQUE (user_id, account_id)
);

CREATE INDEX IF NOT EXISTS agame_baseline_user_idx ON agame_baseline (user_id);


-- ── RPC: upsert_agame_baseline ────────────────────────────────────────────────
--
-- Replaces the single baseline row for (user, account). Idempotent: re-running
-- with the same sessions yields the same row. JSON null → SQL NULL.
--
-- SECURITY DEFINER: called by the recompute pathway via the service-role client.

CREATE OR REPLACE FUNCTION upsert_agame_baseline(
  p_user_id    UUID,
  p_account_id TEXT,
  p_baseline   JSONB
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  INSERT INTO agame_baseline (
    id, user_id, account_id, status,
    session_count, min_session_threshold, confidence_score,
    baseline_stability_score, data_coverage_ratio,
    avg_trade_count, median_trade_count, trade_count_iqr,
    avg_inter_trade_gap_seconds, median_inter_trade_gap_seconds, pace_iqr,
    avg_session_duration_minutes, median_session_duration_minutes,
    avg_position_size, median_position_size, size_variance,
    post_loss_trade_delay_seconds, post_loss_size_change_ratio,
    entry_burst_ratio,
    avg_expectancy, median_expectancy, win_rate,
    computed_at
  ) VALUES (
    (p_baseline->>'id')::uuid,
    p_user_id,
    p_account_id,
    (p_baseline->>'status')::text,
    (p_baseline->>'session_count')::int,
    (p_baseline->>'min_session_threshold')::int,
    (p_baseline->>'confidence_score')::double precision,
    (p_baseline->>'baseline_stability_score')::double precision,
    (p_baseline->>'data_coverage_ratio')::double precision,
    (p_baseline->>'avg_trade_count')::double precision,
    (p_baseline->>'median_trade_count')::double precision,
    (p_baseline->>'trade_count_iqr')::double precision,
    (p_baseline->>'avg_inter_trade_gap_seconds')::double precision,
    (p_baseline->>'median_inter_trade_gap_seconds')::double precision,
    (p_baseline->>'pace_iqr')::double precision,
    (p_baseline->>'avg_session_duration_minutes')::double precision,
    (p_baseline->>'median_session_duration_minutes')::double precision,
    (p_baseline->>'avg_position_size')::double precision,
    (p_baseline->>'median_position_size')::double precision,
    (p_baseline->>'size_variance')::double precision,
    (p_baseline->>'post_loss_trade_delay_seconds')::double precision,
    (p_baseline->>'post_loss_size_change_ratio')::double precision,
    (p_baseline->>'entry_burst_ratio')::double precision,
    (p_baseline->>'avg_expectancy')::double precision,
    (p_baseline->>'median_expectancy')::double precision,
    (p_baseline->>'win_rate')::double precision,
    NOW()
  )
  ON CONFLICT (user_id, account_id) DO UPDATE SET
    id                              = EXCLUDED.id,
    status                          = EXCLUDED.status,
    session_count                   = EXCLUDED.session_count,
    min_session_threshold           = EXCLUDED.min_session_threshold,
    confidence_score                = EXCLUDED.confidence_score,
    baseline_stability_score        = EXCLUDED.baseline_stability_score,
    data_coverage_ratio             = EXCLUDED.data_coverage_ratio,
    avg_trade_count                 = EXCLUDED.avg_trade_count,
    median_trade_count              = EXCLUDED.median_trade_count,
    trade_count_iqr                 = EXCLUDED.trade_count_iqr,
    avg_inter_trade_gap_seconds     = EXCLUDED.avg_inter_trade_gap_seconds,
    median_inter_trade_gap_seconds  = EXCLUDED.median_inter_trade_gap_seconds,
    pace_iqr                        = EXCLUDED.pace_iqr,
    avg_session_duration_minutes    = EXCLUDED.avg_session_duration_minutes,
    median_session_duration_minutes = EXCLUDED.median_session_duration_minutes,
    avg_position_size               = EXCLUDED.avg_position_size,
    median_position_size            = EXCLUDED.median_position_size,
    size_variance                   = EXCLUDED.size_variance,
    post_loss_trade_delay_seconds   = EXCLUDED.post_loss_trade_delay_seconds,
    post_loss_size_change_ratio     = EXCLUDED.post_loss_size_change_ratio,
    entry_burst_ratio               = EXCLUDED.entry_burst_ratio,
    avg_expectancy                  = EXCLUDED.avg_expectancy,
    median_expectancy               = EXCLUDED.median_expectancy,
    win_rate                        = EXCLUDED.win_rate,
    computed_at                     = NOW();
END;
$$;

COMMENT ON FUNCTION upsert_agame_baseline IS
  'Replaces the A-Game baseline row for (user, account). Idempotent. '
  'Derived ONLY from sessions.feature_vector/outcome — recomputable any time.';


-- ── Row Level Security ────────────────────────────────────────────────────────
ALTER TABLE agame_baseline ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'agame_baseline' AND policyname = 'agame_baseline_owner'
  ) THEN
    CREATE POLICY agame_baseline_owner ON agame_baseline
      FOR ALL USING (auth.uid() = user_id);
  END IF;
END $$;


-- ===== 011_recompute_support.sql =====
-- ─────────────────────────────────────────────────────────────────────────────
-- Migration 011: recompute support (Phase B integration — wiring only)
-- ─────────────────────────────────────────────────────────────────────────────
-- Additive, non-destructive. Adds ONE read-only RPC the sweep worker uses to
-- find which (user, account) pairs have trades newer than their last session
-- build. No analytics, no new source of truth.
-- ─────────────────────────────────────────────────────────────────────────────

-- get_dirty_accounts()
-- ────────────────────
-- Returns (user_id, account_id) where the account has trades updated after its
-- most recent session build (or has never been built), EXCLUDING accounts with
-- a replay in progress (avoids the delete-then-rebuild torn-read window).
--
-- Called only by the server-side sweep via the service-role client (global scope).
-- Never exposed to end users.

CREATE OR REPLACE FUNCTION get_dirty_accounts()
RETURNS TABLE (user_id UUID, account_id TEXT)
LANGUAGE sql
STABLE
SECURITY DEFINER
AS $$
  WITH t AS (
    SELECT tr.user_id, tr.account_id, MAX(tr.updated_at) AS last_trade
    FROM   trades tr
    GROUP  BY tr.user_id, tr.account_id
  ),
  s AS (
    SELECT se.user_id, se.account_id, MAX(se.computed_at) AS last_session
    FROM   sessions se
    GROUP  BY se.user_id, se.account_id
  )
  SELECT t.user_id, t.account_id
  FROM   t
  LEFT JOIN s
    ON  s.user_id    = t.user_id
    AND s.account_id = t.account_id
  WHERE (s.last_session IS NULL OR t.last_trade > s.last_session)
    AND NOT EXISTS (
      SELECT 1 FROM position_rebuild_state r
      WHERE  r.user_id    = t.user_id
        AND  r.account_id = t.account_id
        AND  r.replay_in_progress = TRUE
    );
$$;

COMMENT ON FUNCTION get_dirty_accounts IS
  'Accounts whose trades are newer than their last session build (or never built), '
  'excluding replay-in-progress accounts. Used by the recompute sweep worker. '
  'Read-only; no analytics; service-role only.';


