-- ─────────────────────────────────────────────────────────────────────────────
-- Migration 005: executions + trades tables + reconstruction RPCs
-- ─────────────────────────────────────────────────────────────────────────────
-- Run via: supabase db push  (or paste into Supabase SQL editor)
-- Safe to re-run: all statements use IF NOT EXISTS / CREATE OR REPLACE.
-- ─────────────────────────────────────────────────────────────────────────────

-- ── executions ────────────────────────────────────────────────────────────────
-- Stores every raw fill received from any broker.
-- Immutable once inserted — reconstruction reads but never modifies this table.
--
-- Deduplication invariant:
--   UNIQUE(user_id, synthetic_id) ensures each broker fill is stored exactly
--   once per user.  Concurrent inserts for the same fill safely conflict and
--   one wins; the other is a no-op (ON CONFLICT DO NOTHING in the app layer).

CREATE TABLE IF NOT EXISTS executions (
  id              UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id         UUID         NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,

  -- synthetic_id = `${accountId}:${brokerExecId}` — globally unique per user's fills
  -- This is the dedup key and the reconstructor's Execution.id field.
  synthetic_id    TEXT         NOT NULL,

  broker_exec_id  TEXT         NOT NULL,      -- broker's own fill ID (number as string)
  account_id      TEXT         NOT NULL,      -- broker account ID (string for portability)
  symbol          TEXT         NOT NULL,      -- instrument symbol or contractId for MVP
  side            TEXT         NOT NULL CHECK (side IN ('buy', 'sell')),
  qty             INTEGER      NOT NULL CHECK (qty > 0),
  price           NUMERIC(14,6) NOT NULL CHECK (price > 0),
  fill_timestamp  TIMESTAMPTZ  NOT NULL,      -- broker clock — used for reconstruction ordering
  order_id        TEXT,                        -- nullable: absent = reconstructor creates synthetic order
  received_at     BIGINT       NOT NULL,      -- our wall clock (Date.now()), cursor fallback
  raw_payload     JSONB        NOT NULL DEFAULT '{}',  -- original broker object, unmodified
  created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

  CONSTRAINT executions_user_synthetic_uniq UNIQUE (user_id, synthetic_id)
);

-- Reconstruction index: covers the exact WHERE + ORDER BY used by the RPC.
-- Partial index on user_id + symbol + account_id to avoid full-table scans.
CREATE INDEX IF NOT EXISTS executions_reconstruction_idx
  ON executions (user_id, symbol, account_id, fill_timestamp ASC, synthetic_id ASC);

-- ── trades ────────────────────────────────────────────────────────────────────
-- Materialised output of trade reconstruction.
-- Fully derived from executions — can always be regenerated by re-running
-- reconstructTrades() over the executions for a position.
--
-- Invariant: reconstruction_status = 'skipped' means the trade is a complex
-- reversal and MUST be excluded from all P&L aggregations.
-- Queries should always add:  AND reconstruction_status = 'ok'

CREATE TABLE IF NOT EXISTS trades (
  id                    UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id               UUID         NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  account_id            TEXT         NOT NULL,
  symbol                TEXT         NOT NULL,
  direction             TEXT         NOT NULL CHECK (direction IN ('long', 'short')),
  opened_at             TIMESTAMPTZ  NOT NULL,    -- first entry fill timestamp
  closed_at             TIMESTAMPTZ,               -- last exit fill timestamp; NULL = open position
  entry_price           NUMERIC(14,6),             -- order-weighted avg entry; NULL for complex_reversal
  exit_price            NUMERIC(14,6),             -- order-weighted avg exit; NULL for open / reversal
  max_size              INTEGER      NOT NULL CHECK (max_size > 0),
  execution_ids         TEXT[]       NOT NULL DEFAULT '{}',   -- Execution.id values in this trade
  reconstruction_status TEXT         NOT NULL DEFAULT 'ok'
                          CHECK (reconstruction_status IN ('ok', 'skipped')),
  behavioral_tags       TEXT[]       NOT NULL DEFAULT '{}',   -- ["complex_reversal"], ["open"], etc.
  pnl_points            NUMERIC(14,6),             -- raw price-delta × qty; NULL for open / reversal
  net_pnl               NUMERIC(14,6),             -- USD; NULL if instrument unknown / open / reversal
  created_at            TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- Session query index: dashboard loads trades for a user ordered by time.
CREATE INDEX IF NOT EXISTS trades_session_idx
  ON trades (user_id, symbol, account_id, opened_at DESC);

-- Partial index for fast P&L aggregation (excludes skipped trades).
CREATE INDEX IF NOT EXISTS trades_pnl_idx
  ON trades (user_id, opened_at DESC)
  WHERE reconstruction_status = 'ok' AND closed_at IS NOT NULL;

-- updated_at trigger
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger
    WHERE tgname = 'trades_updated_at' AND tgrelid = 'trades'::regclass
  ) THEN
    CREATE TRIGGER trades_updated_at
      BEFORE UPDATE ON trades
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END $$;


-- ── RPC: read_executions_for_reconstruction ───────────────────────────────────
--
-- Reads all executions for a position, sorted, with an advisory lock.
--
-- Lock mechanism
-- ──────────────
-- pg_advisory_xact_lock(key1 int, key2 int) acquires a transaction-scoped
-- advisory lock using two int4 keys.  It blocks until the lock is available
-- and releases automatically when the calling transaction commits or rolls back.
--
-- Two concurrent calls with the same (p_user_id, p_symbol, p_account_id) will
-- serialise: the second waits until the first's transaction ends.  This ensures
-- each caller receives a consistent snapshot — the second caller will always
-- see at least as many rows as the first (inserts are committed before the
-- first call's lock was released).
--
-- hashtext(text) → int4.  Using two keys (user_id, symbol+account) keeps the
-- lock space sparse and reduces false-sharing between unrelated positions.
--
-- SECURITY DEFINER: runs as the function owner (postgres) to bypass RLS.
-- The app layer has already authenticated the caller before invoking this.

CREATE OR REPLACE FUNCTION read_executions_for_reconstruction(
  p_user_id    UUID,
  p_symbol     TEXT,
  p_account_id TEXT
)
RETURNS SETOF executions
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  -- Acquire advisory lock scoped to this (user, symbol, account) triple.
  -- Two reconstructions for the same position serialise here.
  PERFORM pg_advisory_xact_lock(
    hashtext(p_user_id::text),
    hashtext(p_symbol || E'\x00' || p_account_id)
  );

  -- Return sorted executions — ORDER BY enforces INV-5 for the reconstructor.
  RETURN QUERY
    SELECT *
    FROM   executions
    WHERE  user_id    = p_user_id
      AND  symbol     = p_symbol
      AND  account_id = p_account_id
    ORDER BY fill_timestamp ASC, synthetic_id ASC;
END;
$$;

COMMENT ON FUNCTION read_executions_for_reconstruction IS
  'Advisory-locked read of executions for one position. '
  'Serialises concurrent reconstruction triggers for the same (user, symbol, account). '
  'Returns rows sorted (fill_timestamp ASC, synthetic_id ASC) as required by reconstructTrades().';


-- ── RPC: replace_position_trades ─────────────────────────────────────────────
--
-- Atomically replaces all trades for a position with a fresh reconstruction set.
--
-- DELETE + INSERT in a single transaction means there is never a window where
-- a position has zero trade rows.  The app layer passes the full trade set as
-- JSONB so both operations are committed together.
--
-- JSONB null handling:
--   PostgreSQL's ->> operator returns SQL NULL when the JSONB value is JSON null.
--   Casting SQL NULL to a typed column (timestamptz, numeric, etc.) yields SQL NULL.
--   This means null fields in the TypeScript payload round-trip correctly.
--
-- SECURITY DEFINER: same reasoning as above.

CREATE OR REPLACE FUNCTION replace_position_trades(
  p_user_id    UUID,
  p_symbol     TEXT,
  p_account_id TEXT,
  p_trades     JSONB
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  -- Step 1: Remove all existing trades for this position.
  DELETE FROM trades
  WHERE  user_id    = p_user_id
    AND  symbol     = p_symbol
    AND  account_id = p_account_id;

  -- Step 2: If nothing to insert, done.
  IF p_trades IS NULL OR jsonb_array_length(p_trades) = 0 THEN
    RETURN;
  END IF;

  -- Step 3: Insert the full reconstruction set.
  -- JSON null values cast correctly to SQL NULL for nullable columns.
  INSERT INTO trades (
    user_id,
    account_id,
    symbol,
    direction,
    opened_at,
    closed_at,
    entry_price,
    exit_price,
    max_size,
    execution_ids,
    reconstruction_status,
    behavioral_tags,
    pnl_points,
    net_pnl
  )
  SELECT
    p_user_id,
    p_account_id,
    p_symbol,
    (t->>'direction')::text,
    (t->>'opened_at')::timestamptz,
    (t->>'closed_at')::timestamptz,       -- JSON null → SQL NULL ✓
    (t->>'entry_price')::numeric,          -- JSON null → SQL NULL ✓
    (t->>'exit_price')::numeric,           -- JSON null → SQL NULL ✓
    (t->>'max_size')::integer,
    ARRAY(SELECT jsonb_array_elements_text(t->'execution_ids')),
    COALESCE((t->>'reconstruction_status')::text, 'ok'),
    ARRAY(SELECT jsonb_array_elements_text(t->'behavioral_tags')),
    (t->>'pnl_points')::numeric,           -- JSON null → SQL NULL ✓
    (t->>'net_pnl')::numeric               -- JSON null → SQL NULL ✓
  FROM jsonb_array_elements(p_trades) AS t;
END;
$$;

COMMENT ON FUNCTION replace_position_trades IS
  'Atomically replaces all trades for (user_id, symbol, account_id) in one transaction. '
  'Called by the TypeScript ingest layer after reconstruction completes. '
  'DELETE + INSERT ensures no partial-write window.';


-- ── Row Level Security ────────────────────────────────────────────────────────
-- Enable RLS on both tables.  RPCs run as SECURITY DEFINER (postgres) and bypass
-- RLS.  Direct client queries (dashboard) are filtered by user_id.

ALTER TABLE executions ENABLE ROW LEVEL SECURITY;
ALTER TABLE trades     ENABLE ROW LEVEL SECURITY;

-- Users can only read their own data.
-- The service-role client (used by ingest) bypasses RLS entirely.

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'executions' AND policyname = 'executions_owner'
  ) THEN
    CREATE POLICY executions_owner ON executions
      FOR ALL USING (auth.uid() = user_id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'trades' AND policyname = 'trades_owner'
  ) THEN
    CREATE POLICY trades_owner ON trades
      FOR ALL USING (auth.uid() = user_id);
  END IF;
END $$;
