-- ─────────────────────────────────────────────────────────────────────────────
-- Migration 009: sessions (Phase 0 — Behavioural Intelligence)
-- ─────────────────────────────────────────────────────────────────────────────
-- Run via: supabase db push  (or paste into the Supabase SQL editor)
-- Safe to re-run: all statements use IF NOT EXISTS / CREATE OR REPLACE.
--
-- ADDITIVE & NON-DESTRUCTIVE
-- ──────────────────────────
-- This migration ONLY adds a new derived table + one RPC. It does NOT touch
-- event_log, executions, trades, position_rebuild_state, position_snapshots,
-- or rebuild_locks. No existing column, index, policy, or function is altered.
--
-- Architecture
-- ────────────
-- `sessions` is a DERIVED, fully-recomputable materialised view over `trades`:
--
--     event_log (truth) → trades (derived) → sessions (derived, this table)
--
-- It is NOT a source of truth. Every row can be regenerated by running
-- lib/sessions/segment.ts over the user's trades (rebuildSessionsFromTrades).
-- session_id is a deterministic content hash supplied by the app layer, so the
-- same trades always yield the same ids. The natural key
-- (user_id, account_id, start_ts) is the stable reference for downstream layers.
-- ─────────────────────────────────────────────────────────────────────────────

-- ── sessions ──────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS sessions (
  -- Deterministic UUIDv5-style hash of (user, account, start_ts, first_trade_id).
  -- Supplied by the app layer — NOT a random default.
  session_id             UUID         PRIMARY KEY,

  user_id                UUID         NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  account_id             TEXT         NOT NULL,

  -- Session bounds (broker clock, surfaced via trades.opened_at / closed_at).
  start_ts               TIMESTAMPTZ  NOT NULL,   -- first trade opened_at
  end_ts                 TIMESTAMPTZ  NOT NULL,   -- last flat point, or last activity if open

  trade_count            INTEGER      NOT NULL CHECK (trade_count >= 0),

  -- Provenance (TEXT, intentionally NOT a FK to trades: sessions are a derived
  -- cache and must survive trades being replaced/regenerated by replay).
  first_trade_id         TEXT         NOT NULL,
  last_trade_id          TEXT         NOT NULL,

  status                 TEXT         NOT NULL DEFAULT 'closed'
                           CHECK (status IN ('open', 'provisional', 'closed')),

  -- True iff trade_count >= analytics threshold (default 4). Ineligible sessions
  -- are still stored; downstream analytics simply exclude them.
  eligible_for_analysis  BOOLEAN      NOT NULL DEFAULT FALSE,

  -- Phase 1 placeholders. NULL in Phase 0.
  feature_vector         JSONB,
  outcome                JSONB,

  computed_at            TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

  -- Stable natural key — prevents duplicate sessions for the same start.
  CONSTRAINT sessions_user_account_start_uniq UNIQUE (user_id, account_id, start_ts)
);

-- Query index: list a user's sessions (optionally by account) most-recent first.
CREATE INDEX IF NOT EXISTS sessions_user_account_idx
  ON sessions (user_id, account_id, start_ts DESC);

-- Analytics index: eligible sessions only (Phase 1+ baseline/correlation reads).
CREATE INDEX IF NOT EXISTS sessions_eligible_idx
  ON sessions (user_id, account_id, start_ts DESC)
  WHERE eligible_for_analysis = TRUE;


-- ── RPC: replace_user_sessions ────────────────────────────────────────────────
--
-- Atomically replaces ALL sessions for a user with a freshly recomputed set.
-- DELETE + INSERT in a single transaction → idempotent, no duplicate rows, no
-- partial-write window. Re-runnable any number of times.
--
-- The app layer (lib/sessions/segment.ts) computes the full deterministic set
-- and passes it as JSONB. JSON null → SQL NULL via the same ->> cast pattern
-- used by replace_position_trades.
--
-- SECURITY DEFINER: called by the backfill / maintenance pathway using the
-- service-role client, which has already authenticated the caller.

CREATE OR REPLACE FUNCTION replace_user_sessions(
  p_user_id   UUID,
  p_sessions  JSONB
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  -- Step 1: clear all existing sessions for this user.
  DELETE FROM sessions WHERE user_id = p_user_id;

  -- Step 2: nothing to insert → done (a user with no trades has no sessions).
  IF p_sessions IS NULL OR jsonb_array_length(p_sessions) = 0 THEN
    RETURN;
  END IF;

  -- Step 3: insert the recomputed set.
  INSERT INTO sessions (
    session_id, user_id, account_id,
    start_ts, end_ts, trade_count,
    first_trade_id, last_trade_id,
    status, eligible_for_analysis,
    feature_vector, outcome
  )
  SELECT
    (s->>'session_id')::uuid,
    p_user_id,
    (s->>'account_id')::text,
    (s->>'start_ts')::timestamptz,
    (s->>'end_ts')::timestamptz,
    (s->>'trade_count')::integer,
    (s->>'first_trade_id')::text,
    (s->>'last_trade_id')::text,
    (s->>'status')::text,
    (s->>'eligible_for_analysis')::boolean,
    CASE WHEN s->'feature_vector' IS NULL OR s->'feature_vector' = 'null'::jsonb
         THEN NULL ELSE s->'feature_vector' END,
    CASE WHEN s->'outcome' IS NULL OR s->'outcome' = 'null'::jsonb
         THEN NULL ELSE s->'outcome' END
  FROM jsonb_array_elements(p_sessions) AS s;
END;
$$;

COMMENT ON FUNCTION replace_user_sessions IS
  'Atomically replaces all sessions for a user (DELETE + INSERT, one transaction). '
  'Idempotent and safe to re-run. Called by lib/sessions backfill after segmentation. '
  'sessions is a derived cache — event_log/trades remain the sources of truth.';


-- ── Row Level Security ────────────────────────────────────────────────────────
-- Same pattern as every other table: RPC runs SECURITY DEFINER (bypasses RLS);
-- direct client reads are filtered to the owner.

ALTER TABLE sessions ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'sessions' AND policyname = 'sessions_owner'
  ) THEN
    CREATE POLICY sessions_owner ON sessions
      FOR ALL USING (auth.uid() = user_id);
  END IF;
END $$;
